language: clojure
jdk:
  - openjdk11
install:
  - lein deps
  - ./gradlew assemble
script:
  - lein test :all
  - ./gradlew check
after_success:
  - lein cloverage --codecov
  - bash <(curl -s https://codecov.io/bash)
